name: Collection Docs

on:
  push:
    branches:
      - main
      
jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-pr.yml@main
    with:
      init-dest-dir: docs/preview
